uv run skarabina \
    --ms /home/tim/astro/merghers/mergA_tim.ms \
    --flag-nan \
    --flag-clip [0,100] \
    --flag-uv-above 1000 \
    --flag-spectral-window spectral-flags.example.yml \
    --time-average-factor 3 \
    --frequency-average-factor 20 \
    --optimize \
    --msout test_spw.ms \
    --clobber \
    --summary
